markdown: rdiscount 
permalink: /:year/:month/:title 
title: Jiye的网志
url:
subscribe: 
exclude: [ README.md, newpost.rb ]
domain: 
author: Jiye Qian
email: jyq080601@gmail.com
auto: true
twitterID: jiyeqian
googleAnalyticsID: 
disqusShortname: jiyeqian
