markdown: rdiscount 
permalink: /:year/:month/:day/:title 
title: Jiye的网志
url: http://jiyeqian.github.com
subscribe: 
exclude: [ README.md, newpost.rb ]
domain: 
author: Jiye Qian
email: jyq080601@gmail.com
auto: true
twitterID: jiyeqian
googleAnalyticsID: 
disqusShortname: 